data:
  raw_data_path: "data/raw/iris.csv"
  processed_data_path: "data/processed/"
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForestClassifier"
  n_estimators: 100
  random_state: 42
  max_depth: 10

training:
  cv_folds: 5
  scoring: "accuracy"

# MLFlow configuration
mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "iris_hyperparameter_tuning"
  artifact_location: "./mlruns"

# Hyperparameter tuning configuration
hyperparameter_tuning:
  enabled: true
  param_grid:
    n_estimators: [50, 200]
    max_depth: [5, 20]

output:
  model_path: "models/"
  metrics_path: "models/metrics.json"
  plots_path: "models/plots/"